language: node_js
node_js:
  - "0.10"
branches:
  only:
    - feature/ci
before_script:
  - npm install
  - npm install -g gulp
  - npm install -g hexo
  - gulp build
  - cd src/
  - npm install
  - hexo generate